### ISSUE TITLE
[Feat] User 도메인 기능 추가

### ISSUE THREAD

**Issue by yuseung0429** [SolSolHigh/SolSolHigh-BE#20]
## 📔 Description

User 도메인 기능 추가

## 🐈 Todo
- [x] 본 회원 가입
- [x] 닉네임 중복 검사
- [x] 로그아웃
- [x] 세션 유저 정보 조회
- [x] 세션 유저 정보 수정
- [x] 자식 검색
- [x] 등록한 자식 조회
- [x] 등록된 자식 삭제
- [x] 자식 등록 신청
- [x] 자식 등록 신청 승인/거절
- [x] 회원 탈퇴
- [x] 세션 검증
