### ISSUE TITLE
[Feat] Egg 도메인 기능 추가

### ISSUE THREAD

**Issue by khj745700** [SolSolHigh/SolSolHigh-BE#31]
## 📔 Description

Egg  도메인 기능 추가

## 🐈 Todo

- [x] 계란 재화 조회
- [x] 현재 계란 조회
- [x] 현재 계란 깨기 성공
- [x] 소유한 특수 계란 조회
- [x] 특수 계란 가격 조회 (마지막 거래가)
- [x] 팔게요 조회 (이름 검색, 금액별 조회)
- [x] 거래 동향 (일일 평균가 기준)
- [x] 세션이 등록한 팔게요 개시글 조회
- [x] 특별한 계란 거래 등록
- [x] 특별한 계란 거래 요청
- [x] 특별한 계란 거래 내역 조회
