### ISSUE TITLE
[Feat] 사용자 도메인 기능 추가

### ISSUE THREAD

**Issue by yuseung0429** [SolSolHigh/SolSolHigh-BE#35]
## 📔 Description
사용자 도메인 기능 추가

## 🐈 Todo
- [x] 자식이 부모 조회
- [x] 모든 정보 조회에서 성별 추가
- [x] 자식 등록 요청한 부모 조회 (자식 Side)
- [x] 자식 등록 요청한 자식 조회 (부모 Side)
- [x] 부모가 자식 등록 요청 신청 취소
- [x] 레디스 세션 설정파일 분리
