### ISSUE TITLE
[Feat] 서버 내 Event 처리 및 도메인 기능 추가

### ISSUE THREAD

**Issue by khj745700** [SolSolHigh/SolSolHigh-BE#37]
## 📔 Description

이벤트 처리가 난이도가 어느정도 있어, 기능을 단독으로 작성하려 합니다.

## 🐈 Todo

- [x] FCM 등록 기능 추가
- [x] 경험치 조회 기능 추가
- [x] 경험치 로그 조회 기능 추가
- [x] 레벨업 시 약속권 지급 기능 추가
- [x] 계란 깼을 때 특별한 계란 나오는 기능 추가
